### ISSUE TITLE
Bad Docs Config 

### ISSUE THREAD

**Issue by mooncell07** [an-dyy/Lefi#14]
The overall layout is a mess atm, the theme is black + the bg itself is black, links are purple, TOC is not matching at all.

**Comment by anand2312** [comment]
I think it'll be a good idea to group together some pages in the API reference as well (similar to how dpy docs do it). For example: putting stuff like `Guild`, `Member` etc into a `Discord Models` folder. This kind of grouping will reduce clutter and make stuff easier to find.

**Comment by an-dyy** [comment]
I will most likely end up switching from `mkdocs` to `sphinx`, that should solve the searching issue and the theme issue. I will also probably group up models into their own categories like I did for `commands`

**Comment by an-dyy** [comment]
Alrighty I have decided to move from `mkdocs` to `sphinx`, I might also be changing the docstring format to `RST`

**Comment by mooncell07** [comment]
Eh
